version: '3.7'
services:
  web:
    image: forecast:latest
    ports:
      - 8000:5000
    depends_on:
      - mysql
      - redis
    environment:
      DB_HOST: "mysql"
      REDIS_HOST: "redis"
      DATABASE_URL: "mysql+pymysql://docker:docker@mysql/forecast"
      REDIS_URL: "redis://redis"
  scheduler:
    image: forecast:latest
    entrypoint: "/bin/sh ./run_scheduler.sh"
    depends_on:
      - mysql
      - redis
    environment:
      DATABASE_URL: "mysql+pymysql://docker:docker@mysql/forecast"
      DB_HOST: "mysql"
      REDIS_URL: "redis://redis"
      REDIS_HOST: "redis"
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: forecast
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker