"""Add user, weather and cities tables

Revision ID: b1baee26343a
Revises: 
Create Date: 2021-06-12 21:59:00.243590

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b1baee26343a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    city_table = op.create_table('cities',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('cityname', sa.String(length=64), nullable=False),
                    sa.Column('fetched', sa.Boolean(), nullable=False),
                    )
    #op.create_index(op.f('ix_cities_cityname'), 'cities', ['cityname'], unique=True)

    result = []
    with open("most_populated.txt", "r") as citynames:
        content = citynames.read().splitlines()
        for j, city in enumerate(content):
            entry = {'id': j, 'cityname': city, 'fetched': False}
            result.append(entry)
    op.bulk_insert(city_table, result)

    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=64), nullable=True),
                    sa.Column('email', sa.String(length=120), nullable=True),
                    sa.Column('password_hash', sa.String(length=128), nullable=True),
                    sa.Column('token', sa.String(length=32), nullable=True),
                    sa.Column('token_expiration', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('weather',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('cityname', sa.String(length=64), nullable=True),
                    sa.Column('datetime', sa.DateTime(), nullable=True),
                    sa.Column('C', sa.Float(), nullable=True),
                    sa.Column('F', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_weather_C'), 'weather', ['C'], unique=False)
    op.create_index(op.f('ix_weather_F'), 'weather', ['F'], unique=False)
    op.create_index(op.f('ix_weather_cityname'), 'weather', ['cityname'], unique=False)
    op.create_index(op.f('ix_weather_datetime'), 'weather', ['datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_datetime'), table_name='weather')
    op.drop_index(op.f('ix_weather_cityname'), table_name='weather')
    op.drop_index(op.f('ix_weather_F'), table_name='weather')
    op.drop_index(op.f('ix_weather_C'), table_name='weather')
    op.drop_table('weather')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_cities_cityname'), table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
